_.error_on_external_run  # unused attribute (/home/lschmelzeisen/Repositories/wikidated/noxfile.py:22)
_.reuse_existing_virtualenvs  # unused attribute (/home/lschmelzeisen/Repositories/wikidated/noxfile.py:23)
_.stop_on_first_error  # unused attribute (/home/lschmelzeisen/Repositories/wikidated/noxfile.py:24)
test  # unused function (/home/lschmelzeisen/Repositories/wikidated/noxfile.py:44)
_.isLoggable  # unused method (/home/lschmelzeisen/Repositories/wikidated/src/wikidated/_jvm_manager.py:100)
